services:
  web:
    build: .
    ports:
      - 127.0.0.1:8000:8000
    env_file:
      - .env
    volumes:
      - static-volume:/app/static_files
      - db-volume:/app/db

volumes:
  static-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./static_files
  db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db
